name: My first WorkFlow 

on: push 

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo 
          run:  actions/checkout@v4 

        - name: welcome messages
          run: echo "first gitctun action job"
        
        - name: list files
          run: ls 

        - name: read the files
          run : cat README.md
